### ISSUE TITLE
Package still depends on dash

### ISSUE THREAD

**Issue by minad** [tarsius/minions#29]
...despite https://github.com/tarsius/minions/commit/36d39bd25ae58d1359d17f99142520339bea5974

https://github.com/tarsius/minions/blob/4a81446e13f5bfb514e593d0e1c5253a60113301/minions.el#L8

**Comment by minad** [comment]
Generally what is your opinion on dash, s, f? Should the usage of those packages phased out? I found some old discussion thread in the dash repository regarding merging dash and seq.

**Comment by tarsius** [comment]
If I can just use `seq` instead, then I do that. Also for "low-level" packages/libraries I try to avoid `dash`. `borg` for example shouldn't have any third-party dependencies because that would complicate the bootstrapping process and something like `closql` shouldn't for additional dependencies on other packages.

I like `dash` but hardly use any of the more advanced features. Still I am glad that exists too and very occasionally I reach into these parts too. It's good that many packages keep using `dash`, not least because it keeps pressure on Emacs to fill some of the remaining glaring gaps. I miss the equivalent of `-keep` for example (let me know if you know of one).

I do have a bit of a dislike for `f` and `s` though. I don't feel they provide the same befits when writing or reading code that uses `dash`. Sure in that case too I might look up some function/macro too, but then I at least feel like I learned something that I might use myself at some point. When something uses `s-concat` instead of `concat`, then that is just annoying. And I have seen many packages that only used these most trivial third-party functions, nothing that actually adds some value. I have submitted pull-requests to remove such uses, but have given up by now. I feel the new "documentation groups" feature is a better solution to the discoverability problem than an unidiomatic api.

But I really wish I did not have to write `(directory-file-name (file-name-directory (directory-file-name d)))` or similar all the time. That is really annoying and I am sure that alone has driven many people into the arms of `f`.

One thing I don't like about `dash` is the anaphoric variants, which is a bit surprising considering that I originally started using it for `--if-let` and such. While I am slowly moving away from using that particular form and its family I am not again the anaphoric aspect per se (though I am not as much a fan as I used to be), but I think it is awful that this means that every looping macro and functional construct has to be implemented twice, when we could just implement a "compact syntax for short lambda" *once* and be done with it. But sadly the idea of adding a tiny bit of "unnecessary" syntax causes allergic reactions in many and I don't have the strength to make the huge effort it would take to get it into Emacs anyway.

**Comment by minad** [comment]
Okay, thank you for the extensive answer. I agree with all your points basically, in particular regarding `f` and `s`. For me it seems that `seq` mostly supersedes `dash`, since it works on general sequences but with a slightly reduced feature set. It would be good to fill the gaps in `seq`. 

The `-keep` you mentioned, is this not just `mapcar` followed by a `delq nil`? This is probably as good as `-keep` performance wise. Are there other concrete gaps which should be filled? From my experience `seq` works very well in almost all cases and in a few cases where I want mutation, there is `cl-lib`. Of course one can always fallback to imperative style in some performance critical areas.

Regarding the anaphoric variants, I also agree with you that these are unnecessary and that this is better solved with a shorter lambda syntax on the level of Elisp as in your `llama` package. I don't bother too much about the slightly verbose lambda syntax, but it is understandable that people would like a shorter syntax as is present in more modern languages.

Did you propose `llama` for inclusion in Emacs? I would probably use it - but of course only if I wouldn't want to depend on an external package for it, at least not in the long term. The nice thing about your package is that it is backward compatible, for older Emacsen one could depend on a minimal package providing the `##` macro and for newer Emacsen it would be built-in. There is somehow a chicken and egg problem. I would only use `##` only when it gets included in Emacs and Emacs will only include it when `llama` sees some adoption

**Comment by tarsius** [comment]
> The `-keep` you mentioned, is this not just `mapcar` followed by a `delq nil`? This is probably as good as `-keep` performance wise.

Yes, but in some case it is much noisier to do that. When there are several nested loops and lambdas and keeping line length in check (*) is getting tough because the deep nesting, then it is really annoying having to throw an additional `(delq nil ...)` in there.

So yes, it is not essential *at all*, but nice to have. I also feel that adding it anyway would do no harm, especially when considering that similar "unnecessary" things in the same domain already exist. E.g. `cl-filter` is *completely* unnecessary too, when you can just use `mapcan` and some additional noise. In my experience one has to do massive amounts of pleading on `emacs-devel` to get such an "unnecessary" thing added to Emacs. I won't even try. :roll_eyes: 

> Are there other concrete gaps which should be filled?

I think so and hope I will remember to take notes when I stumble into them again. :grinning: 

> Did you propose `llama` for inclusion in Emacs? 

No but earlier implementations were mentioned on the mailing list and the resulting discussions are among those that cause the cynicism that I have put on display above...

----

(*) I meant to ask you to try harder to do that. Thanks for the reminder :grin: . IMO one should stay below 80 most of the time but occasionally going beyond that by a few characters is perfectly okay too. But IMO nearly all the functions from `vertico--sort` till the end of that file are in serious need of a few additional well placed line breaks.

I recommend

```elisp
(use-package display-fill-column-indicator
  :when (version<= "27" emacs-version)
  :config
  (setq-default display-fill-column-indicator-column 80)
  (add-hook 'emacs-lisp-mode-hook 'display-fill-column-indicator-mode)
  (add-hook 'git-commit-setup-hook 'display-fill-column-indicator-mode))
```

**Comment by minad** [comment]
I disagree with the line length limits and I always have. For me 100 columns are fine :)

**Comment by tarsius** [comment]
Okay. I won't argue about it except to say that it is not *just* about line length for me. For example I find that

```elisp
(defun vertico--tidy-shadowed-file ()
  "Tidy shadowed file name, see `rfn-eshadow-overlay'."
  (when (and (eq this-command #'self-insert-command)
             (bound-and-true-p rfn-eshadow-overlay)
             (overlay-buffer rfn-eshadow-overlay)
             (= (point) (point-max))
             (or (>= (- (point) (overlay-end rfn-eshadow-overlay)) 2)
                 (eq ?/ (char-before (- (point) 2)))))
    (delete-region (overlay-start rfn-eshadow-overlay)
		   (overlay-end rfn-eshadow-overlay))))
```

more readable than

```elisp
(defun vertico--tidy-shadowed-file ()
  "Tidy shadowed file name, see `rfn-eshadow-overlay'."
  (when (and (eq this-command #'self-insert-command)
             (bound-and-true-p rfn-eshadow-overlay)
             (overlay-buffer rfn-eshadow-overlay)
             (= (point) (point-max))
             (or (>= (- (point) (overlay-end rfn-eshadow-overlay)) 2)
                 (eq ?/ (char-before (- (point) 2)))))
    (delete-region (overlay-start rfn-eshadow-overlay) (overlay-end rfn-eshadow-overlay))))
```

and I would feel that way even if `rfn-eshadow-overlay` were named `rfn-overlay` and the last line therefore was only 75 characters long.

**Comment by alphapapa** [comment]
>  When something uses `s-concat` instead of `concat`, then that is just annoying.

Agreed, of course.  However, there are other functions in `s` that are useful and concise compared to their non-`s` equivalents.  For example, `s-join`, `s-wrap`, `s-truncate`, and `s-replace` are some that I use frequently.  None of them are essential, of course, but IMHO they make for nicer code.

> But I really wish I did not have to write (directory-file-name (file-name-directory (directory-file-name d))) or similar all the time. That is really annoying and I am sure that alone has driven many people into the arms of f.

Agreed.  I think `f`'s API is generally well designed and a big improvement over Emacs's built-in filename APIs.

> One thing I don't like about dash is the anaphoric variants, which is a bit surprising considering that I originally started using it for --if-let and such. While I am slowly moving away from using that particular form and its family I am not again the anaphoric aspect per se (though I am not as much a fan as I used to be)

I'm generally enthusiastic about anaphoric macros (see *On Lisp*, *Let Over Lambda*, etc).  One of my favorites in `dash` is `--select`, which also combines well with the threading macros.  It makes some code so much more concise and readable.

> For me it seems that seq mostly supersedes dash, since it works on general sequences but with a slightly reduced feature set. It would be good to fill the gaps in seq.

Note that `seq` can be much slower than `dash` (perhaps because it's generic, while `dash` is specific to lists).  For example, see some benchmarks I made here: https://github.com/alphapapa/emacs-package-dev-handbook#diffing-two-lists  In that one, `seq-difference` takes 1.232616 seconds, while `-difference` takes 0.084484.

Also, `dash` generally is intended to imitate Clojure APIs, and is generally non-destructive.  For those who prefer immutable structures, `dash` can be very helpful.  It can help avoid non-obvious bugs caused by unintentionally mutating data.  Even though I don't necessarily have a preference for immutability, I keep encountering this kind of bug in my packages now and then, and using `dash` consistently can help avoid it.

> Regarding the anaphoric variants, I also agree with you that these are unnecessary and that this is better solved with a shorter lambda syntax on the level of Elisp as in your llama package. I don't bother too much about the slightly verbose lambda syntax, but it is understandable that people would like a shorter syntax as is present in more modern languages.

Using `dash`'s anaphoric macros with threading can make code far more concise than using lambdas.  Here's one simple example:

```el
    (->> faces
      (--map (face-attribute it :foreground))
      (--remove (eq 'unspecified it))
      (-remove #'color-gray-p)
      (-select #'background-contrast-p))
```

My two cents.  :)

**Comment by tarsius** [comment]
> Note that `seq` can be much slower than `dash`

Uhuh. I was not expecting that.

**Comment by minad** [comment]
Such performance  differences should not occur. The dash version should be upstreamed to seq. Probably the issue is that the seq version is written to generically and not sufficiently specialized. Like dash, seq is also immutable in contrast to cl-lib.

**Comment by alphapapa** [comment]
Well, here's `seq-difference`:

```el
(cl-defgeneric seq-difference (sequence1 sequence2 &optional testfn)
  "Return a list of the elements that appear in SEQUENCE1 but not in SEQUENCE2.
Equality is defined by TESTFN if non-nil or by `equal' if nil."
  (seq-reduce (lambda (acc elt)
                (if (seq-contains-p sequence2 elt testfn)
                    acc
                  (cons elt acc)))
              (seq-reverse sequence1)
              '()))
```

Here's `-difference`:
```el
(defun -difference (list list2)
  "Return a new list with only the members of LIST that are not in LIST2.
The test for equality is done with `equal',
or with `-compare-fn' if that's non-nil."
  (--filter (not (-contains? list2 it)) list))
```

And `--filter` is:
```el
(defmacro --filter (form list)
  "Return a new list of the items in LIST for which FORM evals to non-nil.
Each element of LIST in turn is bound to `it' and its index
within LIST to `it-index' before evaluating FORM.
This is the anaphoric counterpart to `-filter'.
For the opposite operation, see also `--remove'."
  (declare (debug (form form)))
  (let ((r (make-symbol "result")))
    `(let (,r)
       (--each ,list (when ,form (push it ,r)))
       (nreverse ,r))))
```

And `--each`:
```el

(defmacro --each (list &rest body)
  "Evaluate BODY for each element of LIST and return nil.
Each element of LIST in turn is bound to `it' and its index
within LIST to `it-index' before evaluating BODY.
This is the anaphoric counterpart to `-each'."
  (declare (debug (form body)) (indent 1))
  (let ((l (make-symbol "list"))
        (i (make-symbol "i")))
    `(let ((,l ,list)
           (,i 0)
           it it-index)
       (ignore it it-index)
       (while ,l
         (setq it (pop ,l) it-index ,i ,i (1+ ,i))
         ,@body))))
```

`seq` has a lot more function calls, especially to other `seq` functions, each of which, I guess, dispatches on the type.  I guess the overhead adds up.

And while it might seem nice to upstream the Dash version, I think `seq` is written as it is on purpose.  But I can't speak for Nicolas.
