### ISSUE TITLE
Seems to be incompatible with use of `customize` for `mode-line-format`(?)

### ISSUE THREAD

**Issue by WJCFerguson** [tarsius/minions#33]
`(minions-mode 1)` did not appear to be working for me because I modified my `mode-line` via `customize` and start my emacs as a daemon using `emacsclient -a ""`.

I presume that `setq-default` in the `define-minor-mode` is not compatible with `customize`.  I'm not sure what the solution is.  I'm out of my depth trying to work out what would behave better `default-set-variable` wasn't it.

Obviously I can work around it by not using customize.  Thank you for the package.  Not only does it clean up my modeline it speeds up my startup quite significantly as I was using `delight` which seems remarkably slow.

**Comment by tarsius** [comment]
This is one of those variables that should not be edited using Custom.

In essence what happens is:

```elisp
(setcar (member 'x value)
``

**Comment by WJCFerguson** [comment]
Thanks - seems like a good call to move my custom file load high up in the init.  Perhaps I'm a rare case to hit this, but it could be useful to mention it somewhere as the effect was to just make it look like `(minions-mode 1)` didn't work.

**Comment by tarsius** [comment]
I don't think Minions is the right place to document this. This affects *many* packages and it just so happens that you ran into this problem with this package. The documentation for Custom should make this more clear (if it doesn't already do, I haven't looked).

That being said, since it already talked about similar issues, I added a note to https://github.com/tarsius/minions/wiki.
