### ISSUE TITLE
Incompatible because it depends on Emacs 25.3.

### ISSUE THREAD

**Issue by usharf** [tarsius/minions#7]
Please indicate in README.

**Comment by tarsius** [comment]
Doesn't `package.el` tell you about this?

For a long time I didn't even want to add a `README.md` at all because it is redundant. The same information is supposed to be in the library header and I liked that a simple package didn't need anything but a single file. But Github has changed the expectations and I have come to peace with it. I just don't want to put everything in the `README.md` that one could possibly put there.
